server:
  port: 8080

logging:
  level:
    org.springframework.beans.factory: ERROR
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aftas
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0